name: Matrix Pipeline

on:
  workflow_dispatch:

jobs:
  node:
    runs-on: ["wsl-ubuntu-jai"]
    strategy:
      matrix:
        node-version: [24,26]

    steps:
     - name: clone the code
       uses: actions/checkout@v7

     - name: setup node
       uses: actions/setup-node@v7
       with:
         node-version: ${{matrix.node-version}}

     - name: install dependencies
       run: npm install

     - name: create .env files
       run: |
         echo "PORT=8080" >> .env.development
         echo "APP=GHA-DEV-APP" >> .env.development

         echo "PORT=5000" >> .env.production
         echo "APP=GHA-PROD-APP" >> .env.production

     - name: run node apllication
       run: |
         node app.js &
         sleep 5
         curl http://localhost:8080
         curl http://localhost:8080/health
         pkill -f "node app.js"
       
